
title: MrBoDean's Blog
author: Jon Warnken
description: >- # this means to ignore newlines until "baseurl:"
  Ramblings and observations on Powershell, Automation, Azure, 
  Microsoft Endpoint Manager (Configuration Manager and Intune). 
  And any other random topic that needs to get out of my head. 
baseurl: "/mrbodean-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MrBoDean
github_username:  MrBoDean

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Google services
google_analytics: UA-1101170-4

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
